name: The name of your action here
description: Provide a description here
author: Your name or organization here

branding:
  icon: heart
  color: red

inputs:
  token:
    description: 'GitHub token (if not provided, uses GITHUB_TOKEN env variable)'
    required: false
    default: ''
  webhook-url:
    description: 'Webhook URL for sending the Adaptive Card'
    required: true
  template:
    description: 'Path to the Adaptive Card template'
    required: false
  message1:
    description: 'Custom message to include in the payload'
    required: false
  message2:
    description: 'Custom message to include in the payload'
    required: false
  action-titles:
    description: 'Action titles to include in the payload'
    required: false
  action-urls:
    description: 'Action URLs to include in the payload'
    required: false

runs:
  using: node20
  main: dist/index.js
